# Generated by Django 2.1.3 on 2019-04-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='getadesarunlist',
            name='auction_location',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='engine',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='extra',
            field=models.TextField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='interior_color',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='total_damages',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='transmission',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='wheel_drive',
            field=models.CharField(default='n/a', max_length=50),
        ),

        migrations.AddField(
            model_name='shoppinglist',
            name='auction_location',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='engine',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='extra',
            field=models.TextField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='interior_color',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='total_damages',
            field=models.CharField(default='n/a', max_length=50),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='transmission',
            field=models.CharField(default='n/a', max_length=20),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='wheel_drive',
            field=models.CharField(default='n/a', max_length=50),
        ),
    ]
