# Generated by Django 2.1.3 on 2019-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190409_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getadesarunlist',
            name='GSMR',
        ),
        migrations.RemoveField(
            model_name='getadesarunlist',
            name='MID',
        ),
        migrations.RemoveField(
            model_name='getadesarunlist',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='GSMR',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='MID',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='transactions',
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='check',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='check',
            field=models.TextField(default='n/a'),
        ),
    ]
