# Generated by Django 2.1.3 on 2019-04-09 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190409_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getadesarunlist',
            name='suggested_retail',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='suggested_retail',
        ),
    ]
