# Generated by Django 2.1.3 on 2019-04-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '00015_auto_20190418_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='check',
            field=models.TextField(default='not available'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='check',
            field=models.TextField(default='not available'),
        ),
    ]
