# Generated by Django 2.1.3 on 2019-04-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190425_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getadesarunlist',
            name='transmission',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='check',
            field=models.TextField(default='n/a'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='transmission',
            field=models.TextField(default='n/a'),
        ),
    ]
