# Generated by Django 2.1.3 on 2019-05-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190425_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='getadesarunlist',
            options={},
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='seller_announcements',
            field=models.TextField(default='n/a'),
        ),
    ]
