# Generated by Django 2.1.3 on 2019-05-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190501_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={},
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='total_damages'
        )
    ]
