# Generated by Django 2.1.3 on 2019-05-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190501_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='MMR',
            field=models.TextField(blank=True, default='n/a'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='adesa_id',
            field=models.CharField(blank=True, default='n/a', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='auction_location',
            field=models.CharField(blank=True, default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='check',
            field=models.TextField(blank=True, default='n/a'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='colour',
            field=models.CharField(blank=True, default='Check Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='engine',
            field=models.TextField(blank=True, default='n/a'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='extra',
            field=models.TextField(blank=True, default='n/a'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='grade',
            field=models.CharField(blank=True, default='Check Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='human_valuation',
            field=models.TextField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='interior_color',
            field=models.CharField(blank=True, default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='lane',
            field=models.CharField(blank=True, default='Check Online', max_length=10),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='make',
            field=models.CharField(blank=True, default='Check Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='mileage',
            field=models.CharField(blank=True, default='Check Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='model',
            field=models.CharField(blank=True, default='Check Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='run_no',
            field=models.CharField(blank=True, default='Check Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='seller_announcements',
            field=models.TextField(blank=True, default='n/a'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='transmission',
            field=models.TextField(blank=True, default='n/a'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='trim',
            field=models.CharField(blank=True, default='Check Online', max_length=60),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='wheel_drive',
            field=models.CharField(blank=True, default='n/a', max_length=50),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='year',
            field=models.CharField(blank=True, default='Check Online', max_length=20),
        ),
    ]
