# Generated by Django 2.1.3 on 2019-09-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190523_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageComparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=20)),
                ('year', models.CharField(default='Check Online', max_length=20)),
                ('make', models.CharField(default='Check Online', max_length=20)),
                ('model', models.CharField(default='Check Online', max_length=20)),
                ('trim', models.CharField(default='Check Online', max_length=60)),
                ('adesa_announcements', models.TextField(default='n/a')),
                ('auction_location', models.CharField(default='n/a', max_length=50)),
                ('carfax', models.TextField(default='n/a')),
                ('date', models.CharField(default='Check Online', max_length=20)),
            ],
        ),
    ]
