# Generated by Django 2.1.3 on 2019-09-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190910_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getadesarunlist',
            name='total_damages',
        ),
        migrations.AddField(
            model_name='damagecomparison',
            name='BlackList',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='getadesarunlist',
            name='seller_announcements',
            field=models.TextField(default='n/a'),
        ),
    ]
